tx_90:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin #tx_90_tx_90/IKFastKinematicsPlugin #kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005